[{'parser_class': None,
 'name': 'span',
 'namespace': 'http://www.w3.org/1999/xhtml',
 '_namespaces': {},
 'prefix': None,
 'sourceline': 354,
 'sourcepos': 75,
 'known_xml': False,
 'attrs': {'class': ['answer-text']},
 'contents': ['Certo.'],
 'parent': <li class="answer A"><span class="option">A</span><span class="answer-text">Certo.</span></li>,
 'previous_element': 'A',
 'next_element': 'Certo.',
 'next_sibling': None,
 'previous_sibling': <span class="option">A</span>,
 'hidden': False,
 'can_be_empty_element': False,
 'cdata_list_attributes': {'*': ['class',
 'accesskey',
 'dropzone'],
 'a': ['rel',
 'rev'],
 'link': ['rel',
 'rev'],
 'td': ['headers'],
 'th': ['headers'],
 'form': ['accept-charset'],
 'object': ['archive'],
 'area': ['rel'],
 'icon': ['sizes'],
 'iframe': ['sandbox'],
 'output': ['for']},
 'preserve_whitespace_tags': {'textarea',
 'pre'},
 'interesting_string_types': (<class 'bs4.element.NavigableString'>,
 <class 'bs4.element.CData'>)},
 {'parser_class': None,
 'name': 'span',
 'namespace': 'http://www.w3.org/1999/xhtml',
 '_namespaces': {},
 'prefix': None,
 'sourceline': 354,
 'sourcepos': 169,
 'known_xml': False,
 'attrs': {'class': ['answer-text']},
 'contents': ['Errado.'],
 'parent': <li class="answer B"><span class="option">B</span><span class="answer-text">Errado.</span></li>,
 'previous_element': 'B',
 'next_element': 'Errado.',
 'next_sibling': None,
 'previous_sibling': <span class="option">B</span>,
 'hidden': False,
 'can_be_empty_element': False,
 'cdata_list_attributes': {'*': ['class',
 'accesskey',
 'dropzone'],
 'a': ['rel',
 'rev'],
 'link': ['rel',
 'rev'],
 'td': ['headers'],
 'th': ['headers'],
 'form': ['accept-charset'],
 'object': ['archive'],
 'area': ['rel'],
 'icon': ['sizes'],
 'iframe': ['sandbox'],
 'output': ['for']},
 'preserve_whitespace_tags': {'textarea',
 'pre'},
 'interesting_string_types': (<class 'bs4.element.NavigableString'>,
 <class 'bs4.element.CData'>)}]
